# Generated by Django 6.0.4 on 2026-04-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.AddField(
            model_name='categoria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='fabricante',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fabricante',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='mensagem_promocao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='produto',
            name='promocao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
